version: "3.8"

services:
  app:
    image: "nullstone/phoenix:local"
    volumes:
      - .:/app
      - deps:/app/deps
    ports:
      - "4000:4000"
    environment:
      - NULLSTONE_ENV=local
      - DATABASE_URL=postgres://acme:acme@db:5432/acme
    depends_on:
      - kafka
      - db

  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=acme
      - POSTGRES_PASSWORD=acme
      - POSTGRES_DB=acme

  kafka:
    image: "bitnami/kafka"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka-data:/bitnami

volumes:
  deps:
  kafka-data:
